#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_DIR = ROOT / "apps" / "manifests"
OUTPUT = ROOT / "watch" / "src" / "apps" / "app_registry.generated.inc"
REQUIRED = {
    "id", "name", "version", "entry", "screen", "headline",
    "offline_message", "offline_available",
}
SCREENS = {"HOME", "NOTIFICATIONS", "MUSIC", "ASSISTANT", "SETTINGS"}


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate() -> str:
    rows = []
    ids = set()
    screens = set()
    for path in sorted(MANIFEST_DIR.glob("*.json")):
        manifest = json.loads(path.read_text(encoding="utf-8"))
        missing = REQUIRED - manifest.keys()
        if missing:
            raise ValueError(f"{path.name} missing {sorted(missing)}")
        if manifest["id"] in ids:
            raise ValueError(f"duplicate app id: {manifest['id']}")
        if manifest["screen"] not in SCREENS or manifest["screen"] in screens:
            raise ValueError(f"invalid or duplicate screen: {manifest['screen']}")
        if not isinstance(manifest["version"], int) or manifest["version"] < 1:
            raise ValueError(f"invalid version in {path.name}")
        ids.add(manifest["id"])
        screens.add(manifest["screen"])
        rows.append(
            "\t{ "
            + ", ".join([
                c_string(manifest["id"]),
                c_string(manifest["name"]),
                str(manifest["version"]),
                c_string(manifest["entry"]),
                f"WATCH_SCREEN_{manifest['screen']}",
                c_string(manifest["headline"]),
                c_string(manifest["offline_message"]),
                "true" if manifest["offline_available"] else "false",
            ])
            + " },"
        )
    if screens != SCREENS:
        raise ValueError(f"manifest screens differ: expected {sorted(SCREENS)}")
    return "/* Generated by scripts/generate-app-registry.py. */\n" + "\n".join(rows) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("generated app registry is out of date")
        print("App manifest registry is current.")
    else:
        OUTPUT.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
